---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: rmq-{{ .Values.global.ci_url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 15672
  tls:
  - hosts:
    - rmq-{{ .Values.global.ci_url }}
    secretName: ingress-tls
