---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  serviceName: minio
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        component: {{ .Chart.Name }}
    spec:
      containers:
      - name: minio
        env:
{{- include "minio_envs" . | indent 8 }}
        - name: MINIO_CACHE_DRIVES
          value: "/minio-cache"
        image: minio/minio:RELEASE.2020-11-13T20-10-18Z
        args:
        - server
        - --json
        - /data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
        - name: cache
          mountPath: /minio-cache
{{- if eq .Values.global.env "production" }}
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
{{- end }}
      volumes:
      - name: cache
        emptyDir:
          medium: Memory
{{- if eq .Values.global.tests "yes" }}
      - name: data
        emptyDir: {}
{{- else }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ pluck .Values.global.env .Values.global.system.storageclass | first | default .Values.global.system.storageclass._default }}
      resources:
        requests:
          storage: {{ first (pluck .Values.global.env .Values.minio.storage) | default .Values.minio.storage._default | quote }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: minio
  selector:
    component: {{ .Chart.Name }}
